config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
]

if settings.DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from .views import Home
from bracelets.views import indexview, ItemDetailView

urlpatterns = [
    path('', Home, name='home'),
    path('stock/', indexview, name='all_stock'),
    path('stock/bracelets', indexview, name='bracelet_stock'),
    path('stock/earings', indexview, name='earing_stock'),
    path('stock/item/<int:pk>/', ItemDetailView.as_view(), name='detail')
] 

bracelets/models.py
from random import choice
from django.db import models
from django.utils.html import escape
from django.utils.safestring import mark_safe


class Item(models.Model):
    BRACELET = 'br'
    EARING = 'er'
    OTHER = 'ot'
    TYPE_CHOICES = [
        (BRACELET, 'bracelet'),
        (EARING, 'earing'),
        (OTHER, 'other')
    ]
    title = models.CharField(max_length=200, null=True)
    item_type = models.CharField(max_length=2, choices=TYPE_CHOICES, default=OTHER)
    description = models.TextField(max_length=200, null=True, blank=True)
    price = models.FloatField(default=0.0)
    available = models.IntegerField(default=1)

    @property
    def image_preview(self):
        
        string = ""
        if self.images:
            for represent in self.images.all():
                string += f'''
                        <img 
                        src="{represent.image.url}" 
                        style="
                        width: 300px;
                        height: auto;
                        padding: 10px;
                        margin: 10px;"
                        />
                        '''
            return mark_safe(string)
        return ''
    
    def __str__(self):
        return self.title


class ItemImage(models.Model):
    item = models.ForeignKey(Item, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='bracelets',null=True)

    def __str__(self):
        return f'bracelet for {self.item}'

pages/models.py
from django.db import models

# Create your models here.

bracelets/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Item

def indexview(request):
    object_list = []
    if 'bracelet' in request.path:
        object_list = list(Item.objects.filter(item_type='br'))
    elif 'earing' in request.path:
        object_list = list(Item.objects.filter(item_type='er'))
    else:
        object_list = list(Item.objects.all())
    req_context = {
        'object_list':object_list,
    }
    return render(request, 'index.html', context=req_context)

class ItemDetailView(DetailView):
    model = Item
    template_name = 'item_detail.html'

pages/views.py
from django.views.generic import TemplateView
from django.shortcuts import render
from bracelets.models import Item
from config.settings import SECRET_KEY, DEBUG

def Home(request):
    items = list(Item.objects.all()[:2])
    context = {
        'featured_items': items,
        'test': DEBUG,
    }
    return render(request, 'home.html', context=context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>BRF Chainmail</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <link href="https://fonts.googleapis.com/css2?family=Sora:wght@200&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{% static '/css/base.css' %}">
        <script type="text/javascript" src="{% static 'js/toggle.js' %}" defer></script>
    </head>
    <body>
        <nav class="navbar">
            <div class="brand-title">BRF Chainmail</div>
            <a href="#" class="toggle-button">
                <span class="bar"></span>
                <span class="bar"></span>
                <span class="bar"></span>
            </a>
            <div class="navbar-links">
                <ul>
                    <li><a href="{% url 'home' %}">Home</a></li>
                    <li><a href="{% url 'home' %}">About</a></li>
                    <li><a href="{% url 'all_stock' %}">Available Stock</a></li>
                </ul>
            </div>
        </nav>
        
        
        
        {% block content %}
        {% endblock content %}
        
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
        <div id="banner">
                <h1>BRF Chainmaille</h1>
        </div>
        <div class="all-info">
                <div class="welcome-info">
                        <h1>Welcome!</h1>
                        <p>This is the main webpage for the Chainmaille club from BRF HS. To view our stock, click the button below.
                        To recieve any item that you see on our webpage, bring payment to Mr. Wildenbergs room (rm148) and the products 
                                will be given out on a first come first serve basis.</p>
                        <a href="{% url 'all_stock' %}" style="margin-top: 2vh;">View Our Stock</a>
                </div>
                <div class="about-info">
                        <h1>About</h1>
                        <p>The goal of this site is to give customers a more efficient way of viewing all of the items that they have to choose from in an organized fashion. 
                        There is no guarantee that you will recieve an item you see will still be available when you arrive. So get here quickly!
                        </p>
                        <p><b>Questions?</b> Contact <u>nathan.wildenberg@brf.org</u> or <u>kovartyr23@students.brf.org</u></p>
                </div>
                <div class="featured-items">
                        <h1>Featured Items</h1>
                        <div style="display: flex; flex-direction: column; align-items: center;">
                                {% for item in featured_items %}
                                <a href="{% url 'detail' item.id %}">
                                        <div class="item" style="max-width: 10vw;">
                                                {% with item.images.all|first as imageobj %}
                                                <img class="sized" src="{{ imageobj.image.url }}">
                                                {% endwith %}
                                                <div class="details">
                                                <h2>{{ item.title }}</h2>
                                                <p id="type">({{ item.get_item_type_display }})</p>
                                                <p>Price: ${{ item.price }}0</p>
                                                <p>Available: {{ item.available }}</p>
                                                </div>
                                        </div>
                                </a>
                                {% endfor %}
                        </div>
                </div>
        </div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div id="banner">
        <h1>Available Stock</h1>
    </div>
    <div id="stock-options">
        <ul id="option-links">
            <li><a href="{% url 'all_stock' %}">All</a></li>
            <li><a href="{% url 'bracelet_stock' %}">Bracelets</a></li>
            <li><a href="{% url 'earing_stock' %}">Earings</a></li>
        </ul>
    </div>
    <div class="item-rows">
        {% for bracelet in object_list %}
        <a href="{% url 'detail' bracelet.id %}">
            <div class="item">
                {% with bracelet.images.all|first as imageobj %}
                    <img class="sized" src="{{ imageobj.image.url }}">
                {% endwith %}
                <div class="details">
                    <h2>{{ bracelet.title }}</h2>
                    <p id="type">({{ bracelet.get_item_type_display }})</p>
                    <p>Price: ${{ bracelet.price }}</p>
                    <p>Available: {{ bracelet.available }}</p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
{% endblock content %}

templates/item_detail.html
{% extends 'base.html' %} 
{% block content %} 
<div class="top-info"> 
    <div id="main-info"> 
        <h1>{{ object.title }}</h1> 
        <div id="below-title-info">

            <section>
                <p style="margin: 1vh 0; font-size: 1.4rem;">Price: ${{ object.price }}</p> 
                <p style="margin: 1vh 0; font-size: 1.4rem;">Available: {{ object.available }}</p>
                {% if object.description %}
                    <p style="margin: 1vh 0; font-size: 1.4rem;" class="description">
                        Description: 
                        {{ object.description }}</p>
                {% endif %}
                {% if object.available == 0 %}
                    <div class="out-of-stock">This Item is Currently Unavailable!</div>
                {% endif %}
            </section>
        </div> 
    </div> 
</div> 
<div class="image-gallery-container"> 
    <h1>Image Gallery</h1>
    <p >({{ object.get_item_type_display }})</p>
    <div class="image-gallery">
        {% for imageobj in object.images.all %} 
            <img src="{{ imageobj.image.url }}" class="gallery-image"> 
        {% endfor %} 
    </div>
</div> 
{% endblock content %}